name: fabric-rag-samples
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.9
 - pip
 - pip:
    - numpy==1.24.4
    - openai==1.6.1
    - python-dotenv==1.0.0
    - scikit-learn==1.3.0
    - requests==2.31.0
    - pyyaml==6.0.1
    - psycopg2-binary==2.9.6
    - pandas==2.0.3
    - pgvector==0.2.0
    - langchain==0.0.348
    - docx2txt==0.8
    - docx2pdf==0.1.8
    - tiktoken==0.4.0
    - azure-ai-formrecognizer==3.3.0
    - azure-storage-blob==12.17.0
    - azure-search-documents==11.4.0
    - pydantic==1.10.11
    - black
    - black[jupyter]
    - azure-keyvault==4.2.0
    - python-docx==1.1.0
    - unstructured==0.12.2
    - ipykernel==6.28.0
    - azure-identity==1.16.0 
