name: fabric-rag-samples
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.9
 - pip
 - pip:
    - python-dotenv==1.0.0
    - azure-search-documents==11.4.0
    - azure-keyvault==4.2.0
    - azure-identity==1.16.0 